### ISSUE TITLE
Suggestion for background names and test names 

### ISSUE THREAD

**Issue by Forrestx0** [viren-v/CEseek#1]
I am using your package for the first time. I tried this function: CEscan.out <- CEseek_scanner (input.seqs,a,length.gap,half.gap,match.thres), and it gave me this output with two lists
<img width="504" alt="Screen Shot 2022-08-05 at 8 16 55 PM" src="https://user-images.githubusercontent.com/110702166/183225751-e132fad7-a766-4616-a81e-593ae0e12509.png">
The part of the first list looks like this
<img width="309" alt="Screen Shot 2022-08-05 at 8 18 16 PM" src="https://user-images.githubusercontent.com/110702166/183225791-6ecb5c30-3f52-45da-9dce-85feef2fb15e.png">

and part of the second list looks like this
<img width="761" alt="Screen Shot 2022-08-05 at 8 18 02 PM" src="https://user-images.githubusercontent.com/110702166/183225783-e8bc74a9-ef62-46c1-b634-192e6c9bc911.png">
Does this mean my coding worked? 

Here are my inputs. Then I downloaded your input.seqs from your website and used It as my input. seqs.
<img width="647" alt="Screen Shot 2022-08-05 at 8 23 58 PM" src="https://user-images.githubusercontent.com/110702166/183226068-55263903-3ed4-4b4b-b11a-00f1ccfdde66.png">

And here is my tf.pwms which I named as "a". 
<img width="849" alt="Screen Shot 2022-08-05 at 8 26 47 PM" src="https://user-images.githubusercontent.com/110702166/183226172-f4d4d41f-d8ee-460d-a4e4-e15d2e01ebc5.png">

what inputs do you suggest to change for DNAstringset? Do you have any suggestion for background names and test names for the final output function? (final.output <- seekCEsFromScanned (CEscan.out, test.names, bg.names, p.cut, out.dir, output.html = "no"))

Thank you so much for reading my request.

**Comment by viren-v** [comment]
There are .rds files with this package named test.names (for test sequences) and bg.names(for background names). It should work with second command)

**Comment by Forrestx0** [comment]
Thank you for replying back to me. I wonder if the .rds files will work with all hg38 sequences or do we need to provide our own test names?

**Comment by Forrestx0** [comment]
I tried with your test names and background names. but I got this error message. 
![image](https://user-images.githubusercontent.com/110702166/183741648-d7111d5b-d691-4af6-a72f-d5810c3e0782.png)

Do you have any suggestions for my code?

**Comment by Forrestx0** [comment]
Hi, Can I ask how you generate the testnames and backgroundnames?

**Comment by viren-v** [comment]
Try using a lower p.cut, your desired CEs may not survive this cutoff.

testnames and background names comes from this study:
https://www.nature.com/articles/s41590-019-0565-0
